"""inclucion de tabla token

Revision ID: dd33381576e4
Revises: 2ebe52b56490
Create Date: 2023-02-22 16:46:30.835980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd33381576e4'
down_revision = '2ebe52b56490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tokens', ['token_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('token_id')

    op.drop_table('tokens')
    # ### end Alembic commands ###
